### ISSUE TITLE
Duplicate Battery Status Icons after restart

### ISSUE THREAD

**Issue by hiddensanctum** [mzur/gnome-shell-batime#16]
![Screenshot from 2023-07-13 11-41-32](https://github.com/mzur/gnome-shell-batime/assets/5080145/8fa9825d-24b0-4ada-ae2a-6aa5c64fcdae)

I have weird issue where if I restart my laptop, the original battery icon no longer gets replaced and the extension starts adding duplicate battery icons to the status bar.

**OS:** Ubuntu 22.04.2 LTS
**Device:** Dell XPS 9300
**GNOME version:** 42.9
**Extension version:** 11

**Comment by mzur** [comment]
Do the duplicates disappear when you disable the extension?

**Comment by hiddensanctum** [comment]
No, I have to disable it and restart for them to go away

**Comment by mzur** [comment]
Do you have other extensions installed? If so, try to disable them and see if the issue still occurs.

I also use Ubuntu 22.04.02 and don't see the issue. However, I have GNOME 42.5. How did you get 42.9?

**Comment by hiddensanctum** [comment]
> Do you have other extensions installed? If so, try to disable them and see if the issue still occurs.
> 
> I also use Ubuntu 22.04.02 and don't see the issue. However, I have GNOME 42.5. How did you get 42.9?

Disabled all my extensions and then enable the yours. That seems to have worked. Not sure which extension was causing the issue though.

As for 42.9, I believe I manually upgraded to the latest version to fix another bug
