### ISSUE TITLE
gnome 45 update?

### ISSUE THREAD

**Issue by Neo-29** [mzur/gnome-shell-batime#17]
Can you update this wonderful extension for gnome 45 please ?

**Comment by mzur** [comment]
I'm currently working on GNOME 45 support for another extension but I'll eventually update this one, too.

**Comment by mzur** [comment]
There you go. It was basically a complete rewrite for GNOME 45 but it's much better (and hopefully future-proof) now :wink:

**Comment by Neo-29** [comment]
You're the best 💪. Tks.
