### ISSUE TITLE
Will not load on Gnome 3.32

### ISSUE THREAD

**Issue by Taijian** [mzur/gnome-shell-batime#2]
It seems that Gnome 3.32 broke this extension - it will not load and simply produces the following error message:

Extension "batime@martin.zurowietz.de" had error: TypeError: this._construct is not a function

**Comment by mzur** [comment]
Is there any other distro than Arch where Gnome 3.32 can be installed right now? I need to reproduce the error in order to fix it and I don't want to set up my own Arch installation just for this.

**Comment by Taijian** [comment]
AFAIK VOID Linux has it - OpenSuse Tumbleweed probably also. Manjaro & Antergos should also have it, as they are basically Arch clones, but come with GUI installers, so should be quite a bit easier to set up in a VM.

**Comment by mzur** [comment]
Thanks, I'll give it a try!

**Comment by mzur** [comment]
This should be fixed with the [latest release](https://github.com/mzur/gnome-shell-batime/releases/tag/v1.0.1). It will be available through extensions.gnome.org in a few weeks. Thanks for reporting this issue by the way :+1:

**Comment by Taijian** [comment]
Works great! Thank you for the quick fix!
