### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by Spurlos** [mzur/gnome-shell-batime#21]
Can we expect an official update for this extension to support Gnome 46?

**Comment by mzur** [comment]
Yes but I can't say when I have the time to look at this. Often, it is enough to add the new Shell version to the [supported versions](https://github.com/mzur/gnome-shell-batime/blob/fe492c492db0e3eb225f8cafb0a3f957f3c4d6ae/batime%40martin.zurowietz.de/metadata.json#L4). You find the `metadata.json` file in `~/.local/share/gnome-shell/extensions/batime@martin.zurowietz.de`. Feel free to try this and report back if it works (after a restart).

**Comment by j-zehnder** [comment]
I attempted the fix, it seemed to work. time remaining is all over the place, but I think that is more from the data it is getting and not the extension itself
