### ISSUE TITLE
Request: both battery time and percentage

### ISSUE THREAD

**Issue by luispabon** [mzur/gnome-shell-batime#3]
Great extension, thank you! It would be great to have both percentage and time remaining (to fully charge or discharge, depending on whether we're on AC power) available. Like so:
  
  * When discharging, both time remaining and percentage
  * When charging, both time remaining to full charge and percentage
  * When at 100% and on AC, only percentage

**Comment by mzur** [comment]
Have you tried the [Battery Status](https://extensions.gnome.org/extension/817/battery-status/) extension? It offers some configuration options. Maybe you can get what you like with the right configuration.

I don't intend to add more features to this extension and rather leave it as simple as it is right now. If you absolutely want the different behavior and can't get it with Battery Status, it should be straight forward to build your own extension based on Battery Time. The only thing you need to change is the [power.js](https://github.com/mzur/gnome-shell-batime/blob/master/batime%40martin.zurowietz.de/power.js) file. You can use the [original status indicator](https://gitlab.gnome.org/GNOME/gnome-shell/blob/59edea4bb4e0b2ccbb07fe4fc2b5808641219344/js/ui/status/power.js) as reference.

**Comment by luispabon** [comment]
Fair enough and thanks :+1:
