### ISSUE TITLE
Small font on F31 (Gnome 3.34)

### ISSUE THREAD

**Issue by Mershl** [mzur/gnome-shell-batime#6]
Hello,

If this is intentional, this can be closed or seen as a feature request.
The used font of battery time is smaller than the rest of the panel which looks kind of odd, see screenshot below.

Seen behaviour: Battery time seems to be using the default percentage font/font size which is smaller than the rest of the panel.
Expected behaviour: Battery time uses the same font/font size as the rest of the panel or allows the configuration to do so.

Tested on: Fedora 31 (Gnome 3.34)

![image](https://user-images.githubusercontent.com/520251/77820910-255f1a00-70e6-11ea-951c-11f2b85a746f.png)

**Comment by mzur** [comment]
This is intentional. The default GNOME percentage indicator [uses a smaller font](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/f21a0ff458f834e0f32cd40f2ecd5a5e4b86c8e1/js/ui/status/power.js#L141), too, an I would like to keep this consistent.

**Comment by Mershl** [comment]
Gnome 40 to the rescue :+1: 
![image](https://user-images.githubusercontent.com/520251/117056132-41d37a00-ad1c-11eb-88eb-f137dac40718.png)

Thanks for this extension @mzur!
