### ISSUE TITLE
Support gnome 3.38

### ISSUE THREAD

**Issue by joelostblom** [mzur/gnome-shell-batime#7]
Thanks for making this extension! I am running GNOME Shell 3.38.3 on PopOS (Ubuntu clone) and the extension is not working for me. It installs without errors, but only adds a small space in the top bar (noticeable because the battery icons switches position slightly when the extension is enabled). In the dropdown menu on the gnome shell extensions home page I noticed that there is no version for 3.38, is this why it is not working for me or should the older/newer versions work on 3.38 as well?

**Comment by mzur** [comment]
The extension works in my test VM running Arch with GNOME 3.38.4. Do you have errors in `journalctl /usr/bin/gnome-shell`?

**Comment by joelostblom** [comment]
Fixed, I didn't realize that I needed to enable "Show percentage" in the Gnome tweaks settings for this addon to work. Sorry about that.
